config/routes.rb
Chatter::Application.routes.draw do
  
  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  devise_for :admins
  devise_for :users
  get "/threads/delete/:id" => 'message_thread#destroy_thread'
  get "/threads/archive/:id" => 'message_thread#archive_thread'
  put '/threads/change_subject/' => "message_thread#change_subject"
  get '/users/all' => 'home#allUsers'
  get "/knockout/" => 'home#knockout'
  get "/upload/:message_thread_id" => "messages#upload"
  get "users/sendmail"
   
  post "/upload" => "messages#uploaded"

  resources :lead_replies
  resources :members
  namespace :level2_admin do
    resources :users do
      collection do
        get :logout
      end
    end
    root to: "users#index"
  end

  namespace :account do
    resources :friend_acts
    resources :refertos do
      get :posts, :on => :collection
      get :members, :on => :collection
    end

    resources :posts do
      get :self, :on => :collection

      resources :postreplies
      # resources :refer_tos
    end

    resource :profile do
      resource :avatar

      get :edit_special_acts, :on => :member
      put :skip_step_3, :on => :collection
    end

    resources :special_acts
    
    resources :lead_generations do
      member do
        put :live, :pause
        get :matched, :top_level_match, :unread_replies, :fetch_replies
      end
    end
  end

  namespace :admin do
    resources :users do
      member do
        put :disable, :active
      end
    end
    resources :level2_admins
    resources :badges
    resources :category_badges
    root to: "users#index"
  end

  resources :contacts do
    collection do
      get 'all'
    end
  end

  resources :messages
  resources :message_thread do
    collection do
      get 'list'
    end
    member do
      post 'ack'
      post 'acknowledgement'
    end
  end

  resource :curruser

  resources :quick_message
  resources :groups do
    member do
      post   'addUser'
      delete 'removeUser'
      get    'toAdd'
    end
    collection do
      get 'simpleidx'
    end
  end
  resources :users do
    collection do
      post :update_score
      post :update_task_note
    end
  end
  get "mailer/mailuser"
  get "mailer/recipientid"
  get "mailer/sendmail"
  get "mailer/mailinbox"
  get "mailer/mailnew"
  get "mailer/mailsettings"
  get "mailer/leadmessage"
  get "mailer/mailnotification"
  
  
  
  root to: 'home#knockout'
end

app/models/lead_generation.rb
# == Schema Information
#
# Table name: lead_generations
#
#  id              :integer          not null, primary key
#  lg_type         :string(255)
#  location_id     :integer
#  lg_state        :string(255)      default("live")
#  user_id         :integer
#  rank            :float            default(0.0)
#  lg_product_type :string(255)
#  subject         :text
#  details         :text
#  area_id         :integer
#  area_desc       :text
#  sub_area_id     :integer
#  traveller_id    :integer
#  service_id      :integer
#  start_date      :date
#  end_date        :date
#  is_today        :boolean
#  call_me         :boolean
#  email_me        :boolean
#  proftag         :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class LeadGeneration < ActiveRecord::Base
  include ActionView::Helpers::TextHelper

  attr_accessible :lg_type, :service_id, :area_id, :area_desc, :keyword_list, :details
  attr_accessor :ranking
  belongs_to :user
  # belongs_to :traveller
  belongs_to :location, :class_name => 'Country'
  belongs_to :area
  belongs_to :sub_area, :class_name => 'Area'
  belongs_to :service

  has_and_belongs_to_many :services
  has_and_belongs_to_many :activities
  has_many :lead_replies

  acts_as_taggable_on :keywords

  scope :active_scope, where(:lg_state => 'live')
  scope :match_against_with_live_leads, lambda { |lead_generation|
    match_against(lead_generation)
  }

  scope :match_against, lambda { |lead_generation|
    rs = top_level_match(lead_generation)\
            .tagged_with(Word.expend_with_relationship(lead_generation.keywords), :any => true)

    if lead_generation.sub_area
      rs = rs.where(:sub_area_id => lead_generation.sub_area_id)
    end
    rs
  }

  scope :top_level_match, lambda { |lead|
    rs = active_scope.where{user_id.not_eq lead.user.id}\
    .where(:lg_type => lead.is_providing? ? 'looking_for' : 'providing')\
    .where(:service_id => lead.service_id)

    unless lead.area.try(:is_global?)
      rs = rs.where(:area_id => lead.area.try(:get_matching_ids))
    end

    rs
  }

  def cal_ranking other
    self.ranking = 0
    self.ranking = self.ranking + 5 if self.sub_area_id == other.sub_area_id
    self.ranking = self.ranking + (self.keyword_list.map(&:to_s) & other.keyword_list.map(&:to_s)).size
  end

  def keyword_ranking lead
    rs = 0
    lead.keywords.each do |keyword|
      if word = Word.get_from_real_word(keyword.to_s)

        self.keywords.map(&:to_s).collect {|ele| Word.get_from_real_word(ele)}.each do |self_word|
          if self_word
            if self_word.value.to_s == word.value.to_s
              rs = rs + WordRelation.max_ranking
            else
              rel = WordRelation.related_to_word(word).related_to_word(self_word)
              if !rel.blank?
                rs = rs + rel.first.ranking
              end
            end
          end
        end
      end
    end

    (lead.keywords.map(&:to_s).map(&:downcase).map(&:strip).uniq &
    self.keywords.map(&:to_s).map(&:downcase).map(&:strip).uniq).size.times { rs = rs + 10}

    rs
  end

  def last_replied_at lead
    self.lead_replies.conversations_for(lead, self).order('created_at DESC').first.try(:created_at)
  end

  def mark_replies_read! lead, curr_user
    LeadReply.conversations_for(lead, self).each do |reply|
      if reply.target_lead.user_id == curr_user.id
        reply.read! 
      end
    end
  end

  def unread_replies
    leadid = self.id
    # matchedleadids = LeadGeneration.match_against_with_live_leads(self).map(&:id)
    matchedleadids = LeadGeneration.top_level_match(self).map(&:id)

    LeadReply.includes(:target_lead).includes(:original_lead).where{(target_lead.id.eq leadid) & (original_lead.id.in matchedleadids) & (read.eq false)}
  end

  def unread_replies_count
    self.unread_replies.all.count
  end

  def unread_replies_count_label
    pluralize(self.unread_replies.all.count, 'unread reply')
  end


  def unread_replies_for_particular_lead lead
    selfid = self.id
    LeadReply.conversations_for(lead, self).where{(target_lead.id.eq selfid) & (read.eq false)}
  end

  def cal_ranking!
    rs = LeadReply.related_to_lead(self).count
    mul = Recommend.where(:recommendable_id => self.user.try(:profile).try(:id)).count

    self.rank = rs * (mul + 1)
    self.save(:validate => false)
  end

  # after_create :create_notifications_for_matched_users
  # after_create does not work.. please call this method manually
  # -----------------------------------------------------------------
  def create_notifications_for_matched_users
    if self.is_live?
      matched_leads = LeadGeneration.top_level_match(self).all
      if matched_leads.size > 0
        Notification.create(:lead_generation => self, :user => self.user)
      end

      matched_leads.map(&:user).uniq.each do |user|
        Notification.create(:lead_generation => self, :user => user)
      end
    end
    true
  end

  def prev_latest_reply lead
    last_orinal_lead = LeadReply.conversations_for(lead, self).order('lead_replies.created_at DESC').first.try(:original_lead)
    if last_orinal_lead
      return LeadReply.conversations_for(lead, self).where(:target_lead_id => last_orinal_lead.id).order('lead_replies.created_at DESC').first
    end
    nil
  end

  def get_subject
    self.subject || 'no subject'
  end

  def last_replied_by? lead, user
    latest_reply = LeadReply.conversations_for(lead, self).order('lead_replies.created_at DESC').first
    return true if latest_reply && latest_reply.original_lead.user == user
    false
    # (
    #   curr_user == self.user && last_replied_by_owner?(thread_usr)
    # ) || (
    #   curr_user != self.user && !last_replied_by_owner?(thread_usr)
    # )
  end

  def is_providing?
    self.lg_type == 'providing'
  end

  def is_live?
    self.lg_state == 'live'
  end
  def is_live
    self.is_live?
  end

  def live!
  	self.lg_state = 'live'
  	self.save(:validate => false)
  end

  def pause!
  	self.lg_state = 'pause'
  	self.save(:validate => false)
  end
end

app/controllers/account/lead_generations_controller.rb
class Account::LeadGenerationsController < ApplicationController
  include ActionView::Helpers::TextHelper
  include RepliesHelper
  before_filter :authenticate_user!
  before_filter :check_profile

  def new
  end

  def lead_to_json lead
    lead.to_json(:methods => [:is_live, :unread_replies_count, :unread_replies_count_label], :include => {:area => {}, :sub_area => {:only => :name}, :service => {:only => :name}, :keywords => {:only => :name}, :user => {:methods => [:imageUrlMedium, :name]}})
  end

  def unread_replies
    @lead = current_user.lead_generations.find(params[:id])
    @match = LeadGeneration.find(params[:match_id])

    unread = @lead.unread_replies_for_particular_lead(@match).count

    render :json => {:count => unread, :label => pluralize(unread, 'unread replies')}
  end

  def index
    @body_class = 'grey_bg'
    @leads = current_user.lead_generations

    respond_to do |format|
      format.json { return render(:json => lead_to_json(@leads)) }
      format.html
    end
  end

  def fetch_replies
    @lead = current_user.lead_generations.find(params[:id])
    @target_lead = LeadGeneration.find(params[:match_id])

    @replies = LeadReply.conversations_for(@lead, @target_lead).order('lead_replies.created_at ASC')

    render :json => reply_to_json(@replies)
  end

  def show
    @lead = current_user.lead_generations.find(params[:id])
    @target_lead = LeadGeneration.find(params[:lead_id])

    @replies = LeadReply.conversations_for(@lead, @target_lead).order('lead_replies.created_at ASC')

    @replies.where(:target_lead_id => @lead.id).each do |reply|
      reply.read!
    end
  end

  def matched
    @lead = current_user.lead_generations.find(params[:id])
    
    @matched_leads = LeadGeneration.top_level_match(@lead).order('rank DESC')

    # sort matches with self-rank & keywords rank added up => lead.rank + lead.keyword1.rank + lead.keyword2.rank
    # ===========================================================================================================
    rs = {}
    @matched_leads.each do |lead|
      rs[lead] = lead.keyword_ranking(@lead) + (lead.rank || 0)
    end
    @matched_leads = rs.sort_by {|k, v| v}.reverse.collect {|ele| ele[0]}

    respond_to do |format|
      format.html {}
      format.json { render :json => lead_to_json(@matched_leads) }
    end
  end

  def create
    @lead_generation = current_user.lead_generations.build(params[:lead_generation])

    if params[:from_sign_up]
      profile = current_user.profile
      profile.step = 3
      profile.save(:validate => false)
      if profile.active?
        profile.user.first_time_login!
      end
    end

    if @lead_generation.save && @lead_generation.create_notifications_for_matched_users

      if params[:from_sign_up]
        return redirect_to root_path
      else

        respond_to do |format|
          format.json {return render(:json => lead_to_json(@lead_generation))}
          format.html {return redirect_to account_lead_generations_path, :notice => 'Your Lead created successfully!'}
        end
      end
    else
      return render :json => @lead_generation.errors, :status => :unprocessable_entity
    end

  end

  def update
    @lead_generation = current_user.lead_generations.find(params[:id])
    
    if @lead_generation.update_attributes(params[:lead_generation])
      render :partial => 'lead_generations/show', :locals => {:lead_generation => @lead_generation}, :status => :success, :content_type => 'text/html'
    else
      render :json => @lead_generation.errors, :status => :unprocessable_entity
    end
  end

  def live
    @lead_generation = current_user.lead_generations.find(params[:id])
    @lead_generation.live!

    render :nothing => true, :state => 200, :content_type => 'text/html'
  end

  def top_level_match
    @lead_generation = current_user.lead_generations.find(params[:id])
    matches = LeadGeneration.top_level_match(@lead_generation)
    count = matches.all.size
    render :json => {:count => count, :match_label => pluralize(count, 'match')}.to_json
  end

  def pause
    @lead_generation = current_user.lead_generations.find(params[:id])
    @lead_generation.pause!

    render :nothing => true, :state => 200, :content_type => 'text/html'
  end

  
  def destroy
    @lead_generation = current_user.lead_generations.find(params[:id])
    @lead_generation.destroy

    render :nothing => true, :state => 200, :content_type => 'text/html'
  end
end

app/views/lead_generations/_form.html.haml
- from_sign_up = false if local_assigns[:from_sign_up].nil?
- remote = false if local_assigns[:remote].nil?

%h3 Submit a Lead

.input_area
  %ul.instructions
    %li.one
      I want to sell or offer a service or product is for companies  that want to sell or offer hotel rooms, local tours, travel software, etc. to companies that are looking to buy or find these products and vice versa.

    %li.two 
      Locations need to be matched as well as key words. If you select New Zealand,  the lead will only look for matches in the same country and region if that has been added.
    %li.three
      These keywords are critical in the matching process, so take your time to add plenty of tags you think necessary
    %li.four
      Any additional details you feel is necessary

  = form_for lead_generation, :url => lead_generation.new_record? ? account_lead_generations_path : account_lead_generation_path(lead_generation), :html => {:class => 'form-vertical new_lead_form'}, :remote => remote do |f|

    .control-group.check_box_line.lt
      = f.label :lg_type, 'Are you looking for or offering something?', :class => 'control-label require'
      .controls.radios.no.need_inline
        = f.radio_button :lg_type, 'providing', :checked => true
        = f.label 'I want to sell / offer a service or product', :for => :lead_generation_lg_type_providing
      .controls.radios.need_inline
        = f.radio_button :lg_type, 'looking_for'
        = f.label 'I want to buy / find a service or product', :for => :lead_generation_lg_type_looking_for
        /= f.select :lg_type, [['I want to sell / offer a service or product', 'providing'], ['I want to buy / find a service or product', 'looking_for']], { :include_blank => false, :prompt => 'Select an option'}, :class => 'reinvent-select input-xlarge', :'data-placeholder' => 'true'

    .control-group
      = f.label :service_id, 'What service would you like to trade?', :class => 'control-label require'
      .controls
        = f.collection_select(:service_id, Service.order("name ASC").all, :id, :name, {}, :class => 'reinvent-select', :'data-need-first' => true)

    .control-group
      = f.label :area_id, 'Where are you looking to trade?', :class => 'control-label require'
      .controls.areas
        = render :partial => 'areas/dropdown_selection', :locals => {:propty => :area_id, :areas => Area.country_scope, :as => :lead_generation, :clazz => 'first',  :need_first => true}
        = f.text_field :area_desc, :placeholder => 'City / Town', :class => 'input-normal'

    .control-group.keywords
      = f.label :keyword_list, 'Please type in the key words of the product or service', :class => 'control-label require'
      .controls
        = f.text_field :keyword_list, :placeholder => 'Product / Service Names', :class => 'tagable input-xlarge'


    .control-group.no_underline.details
      = f.label :details, 'Lead Detail', :class => 'control-label'
      / .controls
      / = f.text_field :subject, :placeholder => 'A concise subject', :class => 'input-xlarge'
      .controls
        = f.text_area :details, :placeholder => 'Details'

    - if from_sign_up
      = hidden_field_tag :from_sign_up, 'true'

    .form-actions
      = f.submit 'SUBMIT FOR MATCHING', :class => 'btn btn-primary btn-large btn1', :disable_with => 'Saving...'
      - if from_sign_up
        = link_to 'Skip this step', skip_step_3_account_profile_path, :class => 'btn btn-large', :method => :put, :confirm => 'Are you sure to skip?'

app/views/lead_generations/_form_ko.html.haml
- from_sign_up = false if local_assigns[:from_sign_up].nil?
- remote = false if local_assigns[:remote].nil?

%h3 Submit a Lead

.input_area
  %ul.instructions
    %li.one
      I want to sell or offer a service or product is for companies  that want to sell or offer hotel rooms, local tours, travel software, etc. to companies that are looking to buy or find these products and vice versa.

    %li.two 
      Locations need to be matched as well as key words. If you select New Zealand,  the lead will only look for matches in the same country and region if that has been added.
    %li.three
      These keywords are critical in the matching process, so take your time to add plenty of tags you think necessary
    %li.four
      Any additional details you feel is necessary

  = form_for lead_generation, :url => lead_generation.new_record? ? account_lead_generations_path : account_lead_generation_path(lead_generation), :html => {:'data-bind' => "submit: post_lead", :class => 'form-vertical new_lead_form'} do |f|

    .control-group.check_box_line.lt
      = f.label :lg_type, 'Are you looking for or offering something?', :class => 'control-label require'
      .controls.radios.no.need_inline
        = f.radio_button :lg_type, 'providing', :checked => true
        = f.label 'I want to sell / offer a service or product', :for => :lead_generation_lg_type_providing
      .controls.radios.need_inline
        = f.radio_button :lg_type, 'looking_for'
        = f.label 'I want to buy / find a service or product', :for => :lead_generation_lg_type_looking_for
        /= f.select :lg_type, [['I want to sell / offer a service or product', 'providing'], ['I want to buy / find a service or product', 'looking_for']], { :include_blank => false, :prompt => 'Select an option'}, :class => 'reinvent-select input-xlarge', :'data-placeholder' => 'true'

    .control-group
      = f.label :service_id, 'What service would you like to trade?', :class => 'control-label require'
      .controls
        = f.collection_select(:service_id, Service.order("name ASC").all, :id, :name, {}, :class => 'reinvent-select', :'data-need-first' => true)

    .control-group
      = f.label :area_id, 'Where are you looking to trade?', :class => 'control-label require'
      .controls.areas
        = render :partial => 'areas/dropdown_selection', :locals => {:propty => :area_id, :areas => Area.country_scope, :as => :lead_generation, :clazz => 'first',  :need_first => true}
        = f.text_field :area_desc, :placeholder => 'City / Town', :class => 'input-normal'

    .control-group.keywords
      = f.label :keyword_list, 'Please type in the key words of the product or service', :class => 'control-label require'
      .controls
        = f.text_field :keyword_list, :placeholder => 'Product / Service Names', :class => 'tagable input-xlarge'


    .control-group.no_underline.details
      = f.label :details, 'Lead Detail', :class => 'control-label'
      / .controls
      / = f.text_field :subject, :placeholder => 'A concise subject', :class => 'input-xlarge'
      .controls
        = f.text_area :details, :placeholder => 'Details'

    - if from_sign_up
      = hidden_field_tag :from_sign_up, 'true'

    .form-actions
      = f.submit 'SUBMIT FOR MATCHING', :class => 'btn btn-primary btn-large btn1'
      - if from_sign_up
        = link_to 'Skip this step', skip_step_3_account_profile_path, :class => 'btn btn-large', :method => :put, :confirm => 'Are you sure to skip?'
      - else
        %a.btn.btn-large.btn1{:'data-bind' => "click: view_leads"} Cancel

app/views/lead_generations/_list.html.haml
- view_user = current_user if local_assigns[:view_user].nil?
- for_mail = false if local_assigns[:for_mail].nil?
- conver_lead = nil if local_assigns[:conver_lead].nil?
- show_match_count = false if local_assigns[:show_match_count].nil?
- show_reply_count = false if local_assigns[:show_reply_count].nil?
- is_a_match = false if local_assigns[:is_a_match].nil?
/ - new_entry = false if local_assigns[:new_entry].nil?

.lead_list_new
  / %ul.generation_list
  /   - leads.each_with_index do |lead, index|
  /     %li.lead_generation
  /       = render :partial => 'lead_generations/show', :locals => {:lead_generation => lead, :view_user => view_user, :for_mail => for_mail, :conver_lead => conver_lead, :show_match_count => show_match_count, :show_reply_count => show_reply_count}

  .box_list_new{:'data-bind' => "foreach: leads"}
    .lead_box_new{:'data-bind' => 'visible: !ready_to_rm(), attr: {"data-index": $index}'}
      = render :partial => 'lead_generations/show', :locals => { :view_user => view_user, :for_mail => for_mail, :conver_lead => conver_lead, :show_match_count => show_match_count, :show_reply_count => show_reply_count, :is_a_match => is_a_match}

app/views/lead_generations/_show.html.haml
/ - lead = lead_generation

- conver_lead = nil if local_assigns[:conver_lead].nil?
- dont_need_link = false if local_assigns[:dont_need_link].nil?
- view_user = current_user if local_assigns[:view_user].nil?
/ # - to_conversation = lead_generation.user != view_user if local_assigns[:to_conversation].nil?
- show_details = false if local_assigns[:show_details].nil?
- for_mail = false if local_assigns[:for_mail].nil?

- show_match_count = false if local_assigns[:show_match_count].nil?
- show_reply_count = false if local_assigns[:show_reply_count].nil?
- is_a_match = false if local_assigns[:is_a_match].nil?
/ # - match_lead_url = matched_account_lead_generation_url(lead_generation) 

/ # - actionurl = lead_generation.user == view_user ? match_lead_url : conver_lead.nil? ? '#' : account_lead_generation_url(conver_lead, :lead_id => lead_generation.id)

%section.Leads_section{:'data-bind' => "attr: {'data-lead-id' : id}"}
  .Leads_sectionImg
    %img.avatar_img{:'data-bind' => "attr: {src: user.imageUrlMedium}"}
    %img{:src =>"/assets/users/#{current_user.avatar_file_name}", :class => "currentuserimage"}
    .clear
  .Leads_section_Title
    %span.t1 Snow Boarding
    %span.t1{:'data-bind' => "text: user.id"}
    // %a{:'data-bind' => is_a_match ? "click: $parent.view_conversation" : "click: $parent.view_matches"}
    %p
      %span> Location:
      %span{:'data-bind' => "text: area_text()"}
    %p
      %span> Service Tags:
      %span{:'data-bind' => "text: service.name "}
    .clear

  .Leads_sectionL
    .Leads_sectionL_info
      %p
        %span> Sell / Offer :
        %span{:'data-bind' => "text: service.name "}
      %p
        %span> In :
        %span{:'data-bind' => "text: area_text()"}
    .clear
    .Leads_sectionL_Mesage
      %p{ :'data-bind' => "text: details" }
      %a{:href => "#"} Ref : TT0001
    .clear
  .Leads_sectionR
    .Leads_sectionR1
      %p
        Posted :
        %text{:'data-bind' => "text: created_at"}
      %p
        %span Matched :
        %text{:'data-bind' => "text: top_level_match_label()"}
      %p
        %span New Messages :
        %text 7
    
    = link_to "refer to:", mailer_mailuser_path(id:current_user.id), class: "RT", remote: true
    %span.Live Live
  .Leads_sectionR2 
    = link_to mailer_mailinbox_path(id:current_user.id), class: "RT", remote: true do
      Mail:
      -if unread>0
        %p.mailnoti (#{unread})
      -else
        %p.mailnoti
    
    %input{:type => "hidden", :name => "areain", :'data-bind' => "value: created_at"}
    .clear
  .clear
 

app/views/lead_generations/show.html.haml
.lead_show
  = link_to 'Back to leads', mine_lead_generations_path
  %hr
  = render :partial => 'lead_generations/show', :locals => {:lead_generation => @lead, :show_details => true}

  %ul.reply_users
    - users = (current_user == @lead.user) ? User.related_to_lead(@lead) : [current_user]

    - users.uniq.each do |reply_user|
      %li.reply_user
        - new_reply_for_user = LeadReply.conversations_for_u(reply_user, @lead).where(:target_user_id => current_user.id).where(:read => false).count
        - if new_reply_for_user > 0
          .new_replies_noti
            %span.badge.badge-warning
              = pluralize(new_reply_for_user, 'new reply')

            = link_to 'mark_read', read_replies_lead_generation_path(@lead, :reply_user_id => reply_user.id), :remote => true, :method => :put, :class => 'be_hidden'

        %ul.replies
          - cur_reply = @lead.last_replied_by?(reply_user, current_user)
          - total = LeadReply.conversations_for_u(reply_user, @lead).count

          - prev_reply = @lead.prev_latest_reply(reply_user)
          - LeadReply.conversations_for_u(reply_user, @lead).order('created_at ASC').each_with_index do |reply, index|
            - need_collapse = (index != 0 && index < total - 1) && (cur_reply || (!cur_reply && prev_reply && reply.id <= prev_reply.id ))
            %li.reply{:class =>  need_collapse ? 'need_collapse' : ''}
              = render :partial => 'lead_replies/show', :locals => {:reply => reply}

        .reply_by_current_user
          .user.avatar
            = image_tag current_user.try(:profile).try(:avatar_data).url(:medium) if current_user.try(:profile)
          .body        
            = form_for @lead.lead_replies.build, :remote => true, :html => {:class => :reply_form, :id => "new_lead_reply_for_u_#{reply_user.id}"} do |f|
              = f.hidden_field :lead_generation_id, :value => @lead.id
              = f.hidden_field :target_user_id, :value => reply_user.id
              .input-append
                = f.text_area :body, :placeholder => 'Have something to say?'
                = f.submit 'Submit', :class => 'btn btn-mini btn-primary', :disable_with => 'Submit...'

    - if users.size == 0
      %p No one replied yet!