config/routes.rb
Chatter::Application.routes.draw do
  
  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  devise_for :admins
  devise_for :users
  get "/threads/delete/:id" => 'message_thread#destroy_thread'
  get "/threads/archive/:id" => 'message_thread#archive_thread'
  put '/threads/change_subject/' => "message_thread#change_subject"
  get '/users/all' => 'home#allUsers'
  get "/knockout/" => 'home#knockout'
  get "/upload/:message_thread_id" => "messages#upload"
  get "users/sendmail"
   
  post "/upload" => "messages#uploaded"

  resources :lead_replies
  resources :members
  namespace :level2_admin do
    resources :users do
      collection do
        get :logout
      end
    end
    root to: "users#index"
  end

  namespace :account do
    resources :friend_acts
    resources :refertos do
      get :posts, :on => :collection
      get :members, :on => :collection
    end

    resources :posts do
      get :self, :on => :collection

      resources :postreplies
      # resources :refer_tos
    end

    resource :profile do
      resource :avatar

      get :edit_special_acts, :on => :member
      put :skip_step_3, :on => :collection
    end

    resources :special_acts
    
    resources :lead_generations do
      member do
        put :live, :pause
        get :matched, :top_level_match, :unread_replies, :fetch_replies
      end
    end
  end

  namespace :admin do
    resources :users do
      member do
        put :disable, :active
      end
    end
    resources :level2_admins
    resources :badges
    resources :category_badges
    root to: "users#index"
  end

  resources :contacts do
    collection do
      get 'all'
    end
  end

  resources :messages
  resources :message_thread do
    collection do
      get 'list'
    end
    member do
      post 'ack'
      post 'acknowledgement'
    end
  end

  resource :curruser

  resources :quick_message
  resources :groups do
    member do
      post   'addUser'
      delete 'removeUser'
      get    'toAdd'
    end
    collection do
      get 'simpleidx'
    end
  end
  resources :users do
    collection do
      post :update_score
      post :update_task_note
    end
  end
  get "mailer/mailuser"
  get "mailer/recipientid"
  get "mailer/sendmail"
  get "mailer/mailinbox"
  get "mailer/mailnew"
  get "mailer/mailsettings"
  get "mailer/leadmessage"
  get "mailer/mailnotification"
  
  
  
  root to: 'home#knockout'
end

app/models/category_badge.rb
# == Schema Information
#
# Table name: category_badges
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CategoryBadge < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/admin/category_badges_controller.rb
class Admin::CategoryBadgesController < Admin::BaseController
  # GET /category_badges
  # GET /category_badges.json
  def index
    @category_badges = CategoryBadge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @category_badges }
    end
  end

  # GET /category_badges/new
  # GET /category_badges/new.json
  def new
    @category_badge = CategoryBadge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category_badge }
    end
  end

  # GET /category_badges/1/edit
  def edit
    @category_badge = CategoryBadge.find(params[:id])
  end

  # POST /category_badges
  # POST /category_badges.json
  def create
    @category_badge = CategoryBadge.new(params[:category_badge])

    respond_to do |format|
      if @category_badge.save
        format.html { redirect_to admin_category_badges_path, notice: 'Category badge was successfully created.' }
        format.json { render json: @category_badge, status: :created, location: @category_badge }
      else
        format.html { render action: "new" }
        format.json { render json: @category_badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /category_badges/1
  # PUT /category_badges/1.json
  def update
    @category_badge = CategoryBadge.find(params[:id])

    respond_to do |format|
      if @category_badge.update_attributes(params[:category_badge])
        format.html { redirect_to admin_category_badges_path, notice: 'Category badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category_badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_badges/1
  # DELETE /category_badges/1.json
  def destroy
    @category_badge = CategoryBadge.find(params[:id])
    @category_badge.destroy

    respond_to do |format|
      format.html { redirect_to admin_category_badges_path }
      format.json { head :no_content }
    end
  end
end

app/views/category_badges/_form.html.erb
<%= form_for([:admin, @category_badge]) do |f| %>
  <% if @category_badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_badge.errors.count, "error") %> prohibited this category_badge from being saved:</h2>

      <ul>
      <% @category_badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/category_badges/edit.html.erb
<h1>Editing Category Badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @category_badge %> |
<%= link_to 'Back', admin_category_badges_path %>

app/views/category_badges/index.html.erb
<h1>Listing Category Badges</h1>

<table class="table table-bordered table-hover user_list">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @category_badges.each do |category_badge| %>
  <tr>
    <td><%= category_badge.name %></td>
    <td><%= link_to 'Edit', edit_admin_category_badge_path(category_badge) %>
        <%= link_to 'Destroy', [:admin, category_badge], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category badge', new_admin_category_badge_path %>

app/views/category_badges/new.html.erb
<h1>New Category Badge</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_category_badges_path %>

app/views/category_badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category_badge.name %>
</p>


<%= link_to 'Edit', edit_category_badge_path(@category_badge) %> |
<%= link_to 'Back', category_badges_path %>