config/routes.rb
Chatter::Application.routes.draw do
  
  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  devise_for :admins
  devise_for :users
  get "/threads/delete/:id" => 'message_thread#destroy_thread'
  get "/threads/archive/:id" => 'message_thread#archive_thread'
  put '/threads/change_subject/' => "message_thread#change_subject"
  get '/users/all' => 'home#allUsers'
  get "/knockout/" => 'home#knockout'
  get "/upload/:message_thread_id" => "messages#upload"
  get "users/sendmail"
   
  post "/upload" => "messages#uploaded"

  resources :lead_replies
  resources :members
  namespace :level2_admin do
    resources :users do
      collection do
        get :logout
      end
    end
    root to: "users#index"
  end

  namespace :account do
    resources :friend_acts
    resources :refertos do
      get :posts, :on => :collection
      get :members, :on => :collection
    end

    resources :posts do
      get :self, :on => :collection

      resources :postreplies
      # resources :refer_tos
    end

    resource :profile do
      resource :avatar

      get :edit_special_acts, :on => :member
      put :skip_step_3, :on => :collection
    end

    resources :special_acts
    
    resources :lead_generations do
      member do
        put :live, :pause
        get :matched, :top_level_match, :unread_replies, :fetch_replies
      end
    end
  end

  namespace :admin do
    resources :users do
      member do
        put :disable, :active
      end
    end
    resources :level2_admins
    resources :badges
    resources :category_badges
    root to: "users#index"
  end

  resources :contacts do
    collection do
      get 'all'
    end
  end

  resources :messages
  resources :message_thread do
    collection do
      get 'list'
    end
    member do
      post 'ack'
      post 'acknowledgement'
    end
  end

  resource :curruser

  resources :quick_message
  resources :groups do
    member do
      post   'addUser'
      delete 'removeUser'
      get    'toAdd'
    end
    collection do
      get 'simpleidx'
    end
  end
  resources :users do
    collection do
      post :update_score
      post :update_task_note
    end
  end
  get "mailer/mailuser"
  get "mailer/recipientid"
  get "mailer/sendmail"
  get "mailer/mailinbox"
  get "mailer/mailnew"
  get "mailer/mailsettings"
  get "mailer/leadmessage"
  get "mailer/mailnotification"
  
  
  
  root to: 'home#knockout'
end

app/models/badge.rb
# == Schema Information
#
# Table name: badges
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  point             :integer
#  is_active         :boolean
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  category_badge_id :integer
#

class Badge < ActiveRecord::Base
  attr_accessible :is_active, :name, :point, :category_badge_id

  belongs_to :category_badge

  def self.count_point(badges)
    badges.collect{ |b| b.point }.sum
  end

  def completed_note(current_user)
    note = ""
    completed_badge = UserCompletedBadge.find(:first,
      :conditions => { :user_id => current_user.id, :badge_id => self.id } )
    note = completed_badge.note if completed_badge
    note
  end
  
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @badges }
    end
  end

  # GET /badges/new
  # GET /badges/new.json
  def new
    @badge = Badge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/1/edit
  def edit
    @badge = Badge.find(params[:id])
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(params[:badge])

    respond_to do |format|
      if @badge.save
        format.html { redirect_to admin_badges_path, notice: 'Badge was successfully created.' }
        format.json { render json: @badge, status: :created, location: @badge }
      else
        format.html { render action: "new" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /badges/1
  # PUT /badges/1.json
  def update
    @badge = Badge.find(params[:id])

    respond_to do |format|
      if @badge.update_attributes(params[:badge])
        format.html { redirect_to admin_badges_path, notice: 'Badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge = Badge.find(params[:id])
    @badge.destroy

    respond_to do |format|
      format.html { redirect_to admin_badges_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @badges }
    end
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
    @badge = Badge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/new
  # GET /badges/new.json
  def new
    @badge = Badge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/1/edit
  def edit
    @badge = Badge.find(params[:id])
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(params[:badge])

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render json: @badge, status: :created, location: @badge }
      else
        format.html { render action: "new" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /badges/1
  # PUT /badges/1.json
  def update
    @badge = Badge.find(params[:id])

    respond_to do |format|
      if @badge.update_attributes(params[:badge])
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge = Badge.find(params[:id])
    @badge.destroy

    respond_to do |format|
      format.html { redirect_to badges_url }
      format.json { head :no_content }
    end
  end
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :point %><br />
    <%= f.number_field :point %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :category_badge_id %><br />
    <%= f.number_field :category_badge_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Point</th>
    <th>Is active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @badges.each do |badge| %>
  <tr>
    <td><%= badge.name %></td>
    <td><%= badge.point %></td>
    <td><%= badge.is_active %></td>
    <td><%= link_to 'Show', badge %></td>
    <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
    <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @badge.name %>
</p>

<p>
  <b>Point:</b>
  <%= @badge.point %>
</p>

<p>
  <b>Is active:</b>
  <%= @badge.is_active %>
</p>


<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>